### ISSUE TITLE
Preview images should be optional

### ISSUE THREAD

**Issue by shaneosullivan** [Kudo/react-native-image-carousell#1]
Some apps may want image previews, other may not.  For this to be more reusable, there should be a prop for showPreview

**Comment by Kudo** [comment]
Nice suggestion. Thank you @shaneosullivan, I will do it recently.

**Comment by Kudo** [comment]
Sorry for my late to update this.
I've added a `showPreview` property to v0.1.3 for this case.
Something like

``` jsx
  <ImageCarousell
      dataSource={this.state.dataSource}
      showPreview={false}
  />
```

Thank for your suggestions.
