### ISSUE TITLE
preview images are not getting loaded in "IOS"

### ISSUE THREAD

**Issue by Sarita-tnex** [Kudo/react-native-image-carousell#7]
I am trying to run project on ios but here my preview images are not getting load but its working in android is there any othere way or method so that I can load images.

<View>
          <Image
            style={[
              styles.previewImage,
              previewImageStyle,
              { width: previewImageSize, height: previewImageSize },
              { borderRadius: this.state.borderRad }
            ]}
            source={getImageSourceFromDataSource(row)}
            resizeMode="cover">
          </Image>
          <View style={[styles.onlineStatus, { backgroundColor: this.state.badgeStatus }]} >
          </View>
        </View>

**Comment by Kudo** [comment]
@Sarita-tnex are your images in remote or local? If you try to access remote http URL (without SSL), please make sure your iOS ATS settings are correct.

**Comment by masiamj** [comment]
Running into the same issue. Works great with local images, but can't display anything retrieved dynamically. Any advice?

**Comment by Sarita-tnex** [comment]
@Kudo 
Issue is resolved.We had an issue the way we laid the css for components
